---
title: "README1st: Some Background"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GetStarted}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

Last update: `r format(Sys.time(), '%d %B %Y')` (V2019.2)

---

## What is R?

R is an ever--expanding set of analytical packages that has originated from a small group of programmers starting about the mid--1990's. Urban Myth says they selected the letter "R" as coming from their first names as well as it being a play on the letter "S", "S" being used to identify the S programming language.  Somebody has to be first in line.

R itself is freeware.  On the positive side, it has wonderful analytical and plotting capabilities, and moderate data management capabilities.  On the negative side, you get what you pay for, and since R and its associated packages are free there are many curious idiosyncrasies found in R you will experience.

## How Does R Relate To You and Your Analytical Goals?

R has become the primary tool for data analysis in the broadly defined fields of ecology and conservation, as well as many others.  For better or worse, as of `r format(Sys.time(), '%d %B %Y')` there are about `r as.integer(round(nrow(available.packages())/100)*100)` packages[^1] in R designed around particular analytical tools or processes.  Many of these tools have direct relevance to the data you analyze in ecology and conservation.  Many, unfortunately, do not, or are so trivial in scope they simply are not that useful to your analytical objectives.

[^1]:  Varies somewhat by CRAN site.

The trick to R is finding those packages that are useful.

I cannot, by any stretch of imagination, instruct you in even a small subset of the available R packages in this course.  You have to develop a personal, web--based search pattern to ferret out a package that is relevant to the analyses you wish to perform.  Or better yet, learn how to write your own code to solve your analytical problems. Nonetheless, you will need to invest some measure of personal time above and beyond these courses to learn R.  

## So How Will You Learn R?

**baseR** is one of 11 different workshops I have developed for the analysis of ecological and conservation data within the R environment.  **baseR** -- the first of these -- consists of five modules that introduce you to the basics of R, ranging from how to find and load R onto your personal computer, to data management and manipulation, and ending with basic graphs.  There 22 exercises associated with these modules that can help you master R.  

If you work through the **baseR** modules, and do the exercises, you will have an excellent start on how to use R in your research.  I am, of course, available for consultation on sticky R issues if you are taking any of these courses for credit, and you will encounter many a sticky issue.  I myself do quite regularly.  What I have done personally is develop a "Zen and the Art of R” sense that allows me to rapidly find clues for how to resolve a data management or statistical issue in R.  This can only be learned by experimentation on your part; there is no "spoon-fed” answer to any aspect of R.

## Where to Start

Once you acquire and download a modular ZIP file, say that for **baseR**, unpack the ZIP at any location you prefer on your CPU.  Absent a specific location for this course (and other courses you might be taking), I recommend that you place the file at the \\Users\\YourUserName\\Documents level on a W7/8/10 CPU, or /Users/YourUserName in a MAC, where YourUserName is your W7/8/10 or MAC user name.

Use the navigation links to move around the  workshop.  Pretty self--explanatory.

## I Am an Experienced R User ...

Great!  

Then please skim the exercises (or ignore them!) as you see fit based on your personal level of experience.  There may be some tricks you can learn if you look the exercises over. And if you have some R tricks you wish to share with me, please feel free to do so.  I make no claim to be the Guru of R.  You may also find yourself in the role of helping others in your circle of colleagues.

## I Want To Use My Already Configured System with My Preferred R GUI/IDE/Editor ...

Great again.  

Work with whatever OS or GUI/IDE/Editor you prefer.  Learning R is indifferent to the underlying OS or GUI/IDE/Editor.  That said, it is clear that [RStudio](https://www.rstudio.com/) provides the best current environment for use of R, and if you are a self--defined "newbie" in R I strongly suggest you start there.  

Even Old Curmudgeonly, Command--line, Vanilla R Dinosaurs like myself now incorporate RStudio and its many strengths into analytical processes.

## All I Know About R Is that R Is the 18th Letter of the Alphabet

I'm not going to pretend this is simple for everyone.  

Many of you -- especially students -- have been brought up in a MS EXCEL world.  That is not the world of scientific analysis.  You can, of course, try to analyze your research data within MS EXCEL, and there are many a statistics books based on the use MS EXCEL for what I would define as simple analyses.  There are even several books related to the interplay of MS EXCEL and R.  However, most of you will eventually be doing complex analyses well beyond the capabilities of MS EXCEL.

So learn to useR.

## I Am Taking a Workshop for Credit

Please read the file !README4creditAtUtahState_baseRV2019.2-15Aug2019.pdf as soon as you unzip the baseR-V2019.1.zip file.  It outlines your responsibilities to obtain credit.

